### PR TITLE
Validate if we want the module to manage gitignore

### PR DESCRIPTION
**Pull request by rhoml**
Since not everyone have the same needs in regards to git client configurations it would be nice to be able to decide if we want to manage this file with the module or not.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
If user choose to not manage will they manage in their own? Because I believe they just need to set the global exclude file, and this is already possible.

**Comment by rhoml** [comment]
I think that it should not be related to puppet-git since commonly this is part of users dotfiles which is easier to manage and version.

**Comment by indirect** [comment]
I manage my gitignore via my dotfiles repo, so I am :+1: on this.

**Comment by rhoml** [comment]
Is this mergeable?

**Comment by rgabo** [comment]
It would be great to see this or a similar PR merged as we need to rely on updating per-project .gitignores for things such as IDE setting (`.idea` in our case).

**Comment by jacobbednarz** [comment]
Thanks for this! 🍭

**Comment by rhoml** [comment]
YAY!

**Pull request merged**
