### PR TITLE
Bump git version to 2.5.1 using the Homebrew formula

### PR DESCRIPTION
**Pull request by erichkist**
Hi guys,

I just copy and paste the [git formula from Homebrew](https://github.com/Homebrew/homebrew/blob/1b610fb9a7b2334d0dea550d66a4961840dfc3c2/Library/Formula/git.rb) to `puppet-git`.
Let me know if there is anything else to do. :smile:

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Needs to change here too https://github.com/boxen/puppet-git/blob/master/data/Darwin.yaml#L5

**Comment by erichkist** [comment]
@rafaelfranca Done :wink:

**Comment by rafaelfranca** [comment]
Maybe the tests break now, but let's wait

**Comment by rafaelfranca** [comment]
All green!

**Comment by erichkist** [comment]
I tried to run locally with `script/cibuild` but I had some problems with `librarian-puppet`. Well, the CI is green \o/

**Comment by rafaelfranca** [comment]
Released as 2.7.10

**Pull request merged**
